### ISSUE TITLE
Missing icons of each QAction * of menu bar

### ISSUE THREAD

**Issue by Himanshu40** [BRL-CAD/arbalest#17]
![Screenshot (63)_LI](https://user-images.githubusercontent.com/16383005/170781653-76b977d0-e64b-4471-96e0-5b1e33a26244.jpg)
Icons are already there inside `resources/icons` but seems like `QPushButton *` is not able to set icons.

**Comment by drossberg** [comment]
Currently, there are two "New File" actions (lines 90 and 592 in MainWindow.cpp). It would be good to have only one.

**Comment by Himanshu40** [comment]
> Currently, there are two "New File" actions (lines 90 and 592 in MainWindow.cpp). It would be good to have only one.

So there are two actions for `New, Open, Save, Views, and Raytrace`. So only to keep one action which one we should keep? The `MenuBar` or `ToolBar`?

**Comment by drossberg** [comment]
Right, there are more than just the "New" action duplicated, but let's start with this.

What should be unique is the QAction object. The usual way to do it, is to create this object and `add` it everywhere where needed, e.g. to QMenu or QToolBar objects. But, arbalest has its special toolbar.
